name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to Repo. Your good first issue means a lot'
        pr-message: 'Your first pull request to the repo. This is great. yay!'
